//! Conformance corpus: every document in `tests/corpus` must produce exactly
//! the diagnostic codes its manifest lists. The corpus is generated by
//! `tools/build_corpus.py`, which checks each verdict against lxml.

use std::collections::{BTreeMap, BTreeSet};
use std::path::PathBuf;

use sr_model::{codes, load_file, validate_file, LoadOptions, Severity};

fn corpus() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../tests/corpus")
}

fn manifest() -> BTreeMap<String, BTreeMap<String, Vec<String>>> {
    let text = std::fs::read_to_string(corpus().join("manifest.json")).expect("manifest");
    serde_json::from_str(&text).expect("manifest JSON")
}

#[test]
fn every_document_matches_its_manifest() {
    let m = manifest();
    let mut failures = Vec::new();
    let mut checked = 0;
    for (section, dir) in [("valid", "valid"), ("warnings", "valid"), ("invalid", "invalid")] {
        for (file, expect) in &m[section] {
            let path = corpus().join(dir).join(file);
            let report = validate_file(&path, &LoadOptions::default()).expect("readable");
            let got: BTreeSet<&str> = report.diagnostics.iter().map(|d| d.code.as_str()).collect();
            let want: BTreeSet<&str> = expect.iter().map(String::as_str).collect();
            let errors_ok = match section {
                "invalid" => report.has_errors(),
                _ => !report.has_errors(),
            };
            if got != want || !errors_ok {
                failures.push(format!("{dir}/{file}: expected {want:?}, got {got:?}\n{report}"));
            }
            checked += 1;
        }
    }
    assert!(checked > 100, "corpus too small: {checked}");
    assert!(failures.is_empty(), "{} of {checked} documents disagree:\n{}", failures.len(), failures.join("\n\n"));
}

#[test]
fn corpus_covers_every_rule_and_structural_code() {
    let m = manifest();
    let covered: BTreeSet<&str> = m.values().flat_map(|s| s.values()).flatten().map(String::as_str).collect();
    // Rules of accepted SREPs this engine does not implement yet (the rows of sr_eval::pending::PENDING): the
    // schema carries them, the Rust mirror and the corpus do not. An SREP's rules leave this list with its row.
    const PENDING_RULES: &[&str] = &[
        // SREP 16, connectors
        "C60", "C61", "C62", "C63", "C64", "R48-from", "R48-to", "R49", "R50", "V11",
        // SREP 17, PDF pages and regions
        "C66", "C67", "C68", "C69", "R51", "R52", "V9", // SREP 26, repeat points
        "C74", "C75", "C76", "C77", "C78", "C79", "C80", "V10",
    ];
    let mut missing: Vec<&str> = codes::SCH_ASSERTS
        .iter()
        .map(|a| a.0)
        .filter(|id| !covered.contains(id) && !PENDING_RULES.contains(id))
        .collect();
    for c in ["S01", "S02", "S03", "S04", "S05", "S06", "S07", "S09", "S10", "A01", "A02", "A03", "A04", "W01", "W02"] {
        if !covered.contains(c) {
            missing.push(c);
        }
    }
    assert!(missing.is_empty(), "codes without a corpus document: {missing:?}");
}

#[test]
fn kitchen_sink_loads_into_a_resolved_model() {
    use sr_model::model::{AssetsChild, Node, PaintsChild};
    use sr_model::values::{Color, Rgba};
    use sr_model::{ResolvedPaint, Target};

    let doc =
        load_file(corpus().join("valid/kitchen-sink.scene.xml"), &LoadOptions::default()).expect("valid document");
    assert_eq!(doc.version().as_str(), "1.2");
    assert_eq!(doc.frame_size(), (1920, 1080));
    assert_eq!(doc.fps().to_string(), "30000/1001");
    assert_eq!(doc.frame_count(), 375);
    assert!(doc.warnings().iter().all(|w| w.severity == Severity::Warning));

    // assets and paints resolve by id, with their typed payloads
    assert!(matches!(doc.asset("logo"), Some(AssetsChild::Image(i)) if i.width == 16 && i.representations.len() == 1));
    assert!(matches!(doc.asset("voiceover"), Some(AssetsChild::Generated(_))));
    assert!(matches!(doc.paint("sunset"), Some(PaintsChild::LinearGradient(g)) if g.children.len() == 3));
    assert!(doc.asset("sunset").is_none(), "ids resolve only within their kind");

    // tokens resolve, including tokens used inside gradients
    let bg = doc.resolve_color(&Color::Token("bg".into())).unwrap();
    assert_eq!(bg.to_string(), "#101418ff");
    assert_eq!(doc.resolve_color(&Color::Token("brand".into())), Some(Rgba { r: 1.0, g: 0.5, b: 0.0, a: 1.0 }));
    assert!(matches!(doc.resolve_paint(&doc.scene.project.background), Some(ResolvedPaint::Solid(c)) if c == bg));

    // composition and symbol nodes are addressable by id and by path
    let Some(Node::Layer(title)) = doc.node("title-layer") else { panic!("title-layer is a layer") };
    assert_eq!(title.asset, "title");
    assert_eq!(title.matte.as_deref(), Some("bg"));
    assert!(matches!(doc.node("card-logo"), Some(Node::Layer(_))));
    assert!(matches!(doc.target("card-logo"), Some(Target::Node(p)) if p.steps == vec![1]));
    assert!(matches!(doc.target("root-bone"), Some(Target::Element { name, .. }) if name == "bone"));
    let depth = doc.composition_nodes().iter().map(|(d, _)| *d).max().unwrap();
    assert_eq!(depth, 1);

    // other sections
    assert_eq!(doc.effect("grade").map(|e| e.r#type.as_str()), Some("lut"));
    assert!(doc.light("dome").is_some());
    assert!(doc.marker("drop").is_some());
    assert!(doc.text_style("caption-style").is_some());
    assert!(doc.param("items").is_some() && doc.data_source("rows").is_some() && doc.variant("dark").is_some());
    assert!(doc.audio_track("vo-track").is_some() && doc.bus("fx").is_some());
    assert!(
        doc.caption_track("auto").is_some() && doc.layout("square").is_some() && doc.safe_area("broadcast").is_some()
    );
    assert!(doc.output("master").is_some() && doc.material("chrome").is_some() && doc.symbol("card").is_some());
    assert!(doc.track_data("face").is_some());
    assert_eq!(doc.token("brand").map(|t| t.value.as_str()), Some("1,0.5,0"));

    // defaults are applied
    let Some(Node::Group(hero)) = doc.node("hero") else { panic!() };
    assert_eq!(hero.opacity.get(), 1.0);
    assert!(hero.visible);
    assert_eq!(hero.effects.as_deref(), Some(&["glow-fx".to_string(), "grade".to_string()][..]));
}

#[test]
fn invalid_documents_do_not_load() {
    let err = load_file(corpus().join("invalid/c21.scene.xml"), &LoadOptions::default()).unwrap_err();
    let report = err.report().expect("a validation report");
    assert_eq!(report.codes(), vec!["C21"]);
    let d = &report.diagnostics[0];
    assert!(d.loc.line > 0 && d.path.starts_with("/scene/composition/sequence/transition"));
}
