#!/usr/bin/env python3
"""Writes crates/sr-3d/src/voxel/default_palette.rs from the text of the MagicaVoxel file format description.

The table is `default_palette` of section 8 of MagicaVoxel-file-format-vox.txt in https://github.com/ephtracy/voxel-model (MIT
licence, text in crates/sr-3d/tests/fixtures/vox/real/ephtracy_LICENSE): the colour of palette index c, 0 to 255, as a
little-endian unsigned integer with red in the lowest byte, which is the palette of a file with no RGBA chunk.

Usage: tools/make_default_palette.py PATH-TO-MagicaVoxel-file-format-vox.txt
"""
import re
import sys

text = open(sys.argv[1]).read()
body = text[text.index("default_palette[256]"):]
body = body[body.index("{") + 1 : body.index("};")]
values = [int(v, 16) for v in re.findall(r"0x[0-9a-fA-F]{8}", body)]
assert len(values) == 256, len(values)
rows = []
for c, v in enumerate(values):
    r, g, b, a = v & 255, v >> 8 & 255, v >> 16 & 255, v >> 24 & 255
    rows.append(f"    [{r}, {g}, {b}, {a}],")
out = [
    "//! The palette of a MagicaVoxel file that has no RGBA chunk: the table `default_palette` of section 8 of the description of the file",
    "//! format by the author of MagicaVoxel (https://github.com/ephtracy/voxel-model, MIT licence), read as [red, green, blue, alpha]",
    "//! bytes by palette index, 0 to 255 (index 0 is empty). Generated by `tools/make_default_palette.py`; do not edit.",
    "",
    "pub const DEFAULT_PALETTE: [[u8; 4]; 256] = [",
    *rows,
    "];",
    "",
]
open("crates/sr-3d/src/voxel/default_palette.rs", "w").write("\n".join(out))
print(len(values), "entries")
