#!/usr/bin/env python3
"""Performance gate: is HEAD slower than BASE on the same machine?

usage: tools/perf_gate.py BASE_BIN HEAD_BIN [--fixtures NAME,...] [--rounds N]
                          [--threshold FRACTION] [--work DIR] [--json OUT]

Benches each fixture (render --bench) with the two scene-render binaries in alternating
rounds, BASE then HEAD, N times (default 3), and compares each binary's best median frame
time: the fastest round is the one least disturbed by whatever else the machine was doing.
A fixture regresses when HEAD's best is more than FRACTION (default 0.15) slower than
BASE's; any regression makes the exit status 1, a failed run 2. Both binaries render the
same fixture files, generated by this checkout's tools (see tools/perf_common.py), under
the same environment (SR_GPU_BACKEND=vulkan unless set), so only the renderer differs.

Fixtures and frames: perf_impact 0..30 (tools/perf_impact.py: posterize-time, strokes,
particles, motion blur, adjustments, grain) and perf_effects 0..30 (tools/perf_effects.py).
With --json, writes {"threshold": ..., "fixtures": {name: {"base_ms", "head_ms", "ratio",
"regressed", "base_runs", "head_runs"}}}.
"""
import argparse
import json
import re
import subprocess
import sys

import perf_common

FRAMES = {"perf_impact": "0..30", "perf_effects": "0..30"}

MEDIAN = re.compile(r"^render: median ([0-9.]+) ms", re.M)


def median_ms(stdout):
    """The median frame time of a `render --bench` run."""
    m = MEDIAN.search(stdout or "")
    if not m:
        raise ValueError("no 'render: median' line in the bench output")
    return float(m.group(1))


def verdict(base_runs, head_runs, threshold):
    """Compares the best (lowest) median of each binary's runs."""
    base, head = min(base_runs), min(head_runs)
    ratio = head / base if base > 0 else float("inf")
    return {
        "base_ms": base,
        "head_ms": head,
        "ratio": round(ratio, 4),
        "regressed": ratio > 1.0 + threshold,
        "base_runs": list(base_runs),
        "head_runs": list(head_runs),
    }


def bench(binary, scene, frames, env, timeout=1800):
    r = subprocess.run(
        [binary, "--color", "never", "render", scene, "--bench", "--frames", frames],
        capture_output=True,
        text=True,
        env=env,
        timeout=timeout,
    )
    if r.returncode != 0:
        raise RuntimeError(f"{binary} exited {r.returncode}: {perf_common.tail(r.stderr or r.stdout)}")
    return median_ms(r.stdout)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("base")
    ap.add_argument("head")
    ap.add_argument("--fixtures", default=",".join(FRAMES))
    ap.add_argument("--rounds", type=int, default=3)
    ap.add_argument("--threshold", type=float, default=0.15)
    ap.add_argument("--work", default=perf_common.DEFAULT_WORK)
    ap.add_argument("--json")
    a = ap.parse_args(argv)
    env = perf_common.run_env()
    results = {}
    failed = False
    for name in [n.strip() for n in a.fixtures.split(",") if n.strip()]:
        try:
            scene = perf_common.fixture_scene(a.work, name, log=lambda m: print(m, flush=True))
            runs = {"base": [], "head": []}
            for k in range(a.rounds):
                for which, binary in (("base", a.base), ("head", a.head)):
                    ms = bench(binary, scene, FRAMES.get(name, "0..30"), env)
                    runs[which].append(ms)
                    print(f"{name} round {k + 1} {which}: {ms:.3f} ms", flush=True)
            results[name] = verdict(runs["base"], runs["head"], a.threshold)
        except (perf_common.FixtureError, RuntimeError, ValueError, subprocess.TimeoutExpired) as e:
            print(f"{name}: FAILED: {e}", flush=True)
            results[name] = {"error": str(e)}
            failed = True
    print(f"\n{'fixture':<16} {'base ms':>10} {'head ms':>10} {'head/base':>10}")
    for name, v in results.items():
        if "error" in v:
            print(f"{name:<16} {'failed':>10}")
            continue
        flag = "  REGRESSION" if v["regressed"] else ""
        print(f"{name:<16} {v['base_ms']:>10.3f} {v['head_ms']:>10.3f} {v['ratio']:>10.3f}{flag}")
    if a.json:
        with open(a.json, "w") as f:
            json.dump({"threshold": a.threshold, "fixtures": results}, f, indent=2)
    if failed:
        return 2
    return 1 if any(v.get("regressed") for v in results.values()) else 0


if __name__ == "__main__":
    sys.exit(main())
